# Generated by Django 5.2.17 on 2026-10-04 19:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("editor", "0001_initial"),
        ("stories", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="aicall",
            name="outcome",
            field=models.CharField(
                choices=[
                    ("success", "Success"),
                    ("provider_error", "Provider error"),
                    ("timeout", "Timeout"),
                    ("empty", "Empty response"),
                    ("quota", "Quota"),
                ],
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="ReviewFinding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("anchor", models.TextField(blank=True)),
                ("question", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Open"), ("dismissed", "Dismissed")],
                        default="open",
                        max_length=16,
                    ),
                ),
                ("model", models.CharField(max_length=128)),
                (
                    "kind",
                    models.CharField(
                        choices=[("question", "Question"), ("gap", "Gap")],
                        default="question",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "asked_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_findings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "chapter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_findings",
                        to="stories.chapter",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
                "indexes": [
                    models.Index(
                        fields=["chapter", "status"],
                        name="editor_revi_chapter_e1225f_idx",
                    )
                ],
            },
        ),
    ]
