# Generated by Django 6.1.1 on 2026-10-05 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("editor", "0002_review_finding"),
    ]

    operations = [
        migrations.AddField(
            model_name="reviewfinding",
            name="quote",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name="reviewfinding",
            name="start_offset",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
