# Generated by Django 6.1.1 on 2026-10-05 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("editor", "0003_review_finding_anchor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reviewfinding",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("dismissed", "Dismissed"),
                    ("superseded", "Superseded"),
                ],
                default="open",
                max_length=16,
            ),
        ),
    ]
