# Generated by Django 5.2.16 on 2026-07-12 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stories", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chapter",
            name="content_format",
            field=models.CharField(
                choices=[("plain", "Plain Text"), ("html", "Rich Text (HTML)")],
                default="plain",
                max_length=10,
            ),
        ),
    ]
