# Generated by Django 5.2.16 on 2026-07-12 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="authorprofile",
            name="stripe_connect_onboarded",
            field=models.BooleanField(default=False),
        ),
    ]
